public class iplScoreCard {
    public static void matchFixtures(){
        Integer noOfTeams = 8;
		Integer matchesPerTeam = 11;
		Integer pointsPerMatch = 2;

        List<String>teamList = new List<String>{'Chennai SuperKings', 'Mumbai Indians', 'Sunrises Hyderabad', 'Delhi Capitals', 'Rajasthan Royals', 'Kolkatta Knight riders', 'Kings X1 Punjab', 'Royal Challengers Banglore'};
        System.debug('IPL teams :'  +teamList);
    
    }
}